<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>CartModify</name>
   <tag></tag>
   <elementGuidId>fc421312-d7ae-4504-be97-f83008f9d5f3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <restRequestMethod></restRequestMethod>
   <restUrl></restUrl>
   <serviceType>SOAP</serviceType>
   <soapBody>&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?>&lt;SOAP-ENV:Envelope xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:tns=&quot;http://webservices.amazon.com/AWSECommerceService/2011-08-01&quot;>
  &lt;SOAP-ENV:Header/>
  &lt;SOAP-ENV:Body>
    &lt;tns:CartModify>
      &lt;tns:MarketplaceDomain>?&lt;/tns:MarketplaceDomain>
      &lt;tns:AWSAccessKeyId>?&lt;/tns:AWSAccessKeyId>
      &lt;tns:AssociateTag>?&lt;/tns:AssociateTag>
      &lt;tns:Validate>?&lt;/tns:Validate>
      &lt;tns:XMLEscaping>?&lt;/tns:XMLEscaping>
      &lt;tns:Shared>?&lt;/tns:Shared>
      &lt;tns:Request>?&lt;/tns:Request>
    &lt;/tns:CartModify>
  &lt;/SOAP-ENV:Body>
&lt;/SOAP-ENV:Envelope>
</soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod>SOAP</soapRequestMethod>
   <soapServiceFunction>CartModify</soapServiceFunction>
   <wsdlAddress>http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl</wsdlAddress>
</WebServiceRequestEntity>
